// Copyright 2025 Intelligent Robotics Lab
//
// This file is part of the project Easy Navigation (EasyNav in short)
// licensed under the GNU General Public License v3.0.
// See <http://www.gnu.org/licenses/> for details.

#ifndef EASYNAV_MPC_CONTROLLER__MPCCONTROLLER_HPP_
#define EASYNAV_MPC_CONTROLLER__MPCCONTROLLER_HPP_

#include <memory>
#include <expected>
#include <string>
#include <vector>
#include <Eigen/Core>
#include <nlopt.hpp>
#include <cmath>

#include <tf2/LinearMath/Quaternion.hpp>
#include <tf2/LinearMath/Matrix3x3.hpp>
#include "geometry_msgs/msg/pose.hpp"
#include "geometry_msgs/msg/pose_stamped.hpp"
#include "geometry_msgs/msg/twist_stamped.hpp"
#include "nav_msgs/msg/odometry.hpp"
#include "nav_msgs/msg/path.hpp"
#include "visualization_msgs/msg/marker.hpp"
#include "visualization_msgs/msg/marker_array.hpp"

#include "easynav_core/ControllerMethodBase.hpp"
#include "easynav_common/types/NavState.hpp"

struct MPCParameters
{
  Eigen::Vector2d goal;
  Eigen::Vector3d x0;
  Eigen::Vector3d theta0;
  Eigen::Matrix2d Q;
  Eigen::Matrix2d R;
  Eigen::Matrix2d Rd;
  double qtheta;
  int N;
  double dt;
};

namespace easynav
{

/// \brief A MPC Controller.
class MPCController : public ControllerMethodBase
{
public:
  MPCController();

  /// \brief Destructor.
  ~MPCController() override;

  /// \brief Initializes parameters and MPC controller.
  /// \return std::expected<void, std::string> success or error message.
  std::expected<void, std::string> on_initialize() override;

  /// \brief Updates the controller using the given NavState.
  /// \param nav_state Current navigation state, including odometry and planned path.
  void update_rt(NavState & nav_state) override;

  /// \brief Publishes the selected path by MPC controller
  /// \param pose Eigen::Vector3d of the robot
  /// \param best_path Path generated by MPC
  void publish_mpc_path(
    const Eigen::Vector3d & position, const Eigen::Vector3d & orientation,
    const std::vector<double> & best_path);

protected:
  int horizon_steps_{5};      ///< Prediction horizon for MPC.
  double dt_{0.1};            ///< Time step for MPC.
  double max_lin_vel_{1.5};   ///< Maximum linear velocity for MPC.
  double max_ang_vel_{1.5};   ///< Maximum angular velocity for MPC.
  bool verbose_{false};       ///< Value to debug on terminal

  rclcpp::Publisher<visualization_msgs::msg::MarkerArray>::SharedPtr mpc_path_pub_;    ///< Publisher for MPC path markers.

private:
  Eigen::Matrix2d Q_ {{4.0, 0.0}, {0.0, 4.0}};    ///< Tracking Cost
  Eigen::Matrix2d R_ {{0.1, 0.0}, {0.0, 0.1}};  ///< Effort Cost
  Eigen::Matrix2d Rd_ {{0.1, 0.0}, {0.0, 0.1}};   ///< Smooth Cost
  double qtheta_ {3.0};
  geometry_msgs::msg::TwistStamped cmd_vel_;  ///< Current velocity command.

};

}  // namespace easynav

#endif  // EASYNAV_MPC_CONTROLLER__MPCCONTROLLER_HPP_
